### ISSUE TITLE
Wrap calls to RED.node.registeryType() in try catch

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge-nr-file-nodes#1]
### Description

To make these nodes only load if the core file nodes are disabled and make sure they fail cleanly

**Comment by Steve-Mcl** [comment]
Ben, 

do you mean the JS code calls (https://github.com/flowforge/nr-file-nodes/blob/b4be8ae395721b3b77f55d340c205ce12e8421dd/file.js#L219)

or HTML code calls (https://github/flowforge/nr-file-nodes/blob/b4be8ae395721b3b77f55d340c205ce12e8421dd/file.html#L202) 

Or both?

I thought they had to throw an error to avoid installation?  Or is it just that we want them to fail quietly?

**Comment by Steve-Mcl** [comment]
@ben, @knolleary 

Looking at this. The "error" surfaces as a warning and serves as an indicator that the built in file nodes were not disabled...



![Image](https://user-images.githubusercontent.com/44235289/202665635-01c6613d-d9be-4542-84cb-cc5f75b01649.png)


Please advise on direction

**Comment by hardillb** [comment]
I mean the calls in the `js` file.

As things are it works as intended, but I'd like to remove the Node-RED warning and print something more meaningful

**Comment by Steve-Mcl** [comment]
ok, gotcha. 

How does (1) "The FlowForge file nodes cannot be loaded when the built-in file nodes are enabled" sound?

Or (2) "The FlowForge file nodes cannot be loaded. Please disable the built-in file nodes"

Or (3) "The FlowForge file nodes cannot be loaded. Please disable the built-in file nodes under the nodesExcludes array in your settings file"

Or (4) "<your suggestion here :)"

**Comment by hardillb** [comment]
Having tested this, I  now don't think it will work as there doesn't appear to be a way to intercept the failure to register or to get a list of the already registered nodes at load time.

**Comment by Steve-Mcl** [comment]
Shall we move this to the backlog Ben (get it off the 1.1 milestone) - or even close it?

**Comment by Steve-Mcl** [comment]
Only resolution I see here is to close this. Please re-open if necessary.
